variable "project_name"              { type = string }
variable "environment"               { type = string }
variable "location"                  { type = string }
variable "resource_group_name"       { type = string }
variable "tenant_id"                 { type = string }
variable "deployer_object_id"        { type = string }
variable "sku"                       { type = string
  default = "standard" }
variable "soft_delete_retention_days" { type = number
  default = 7 }
variable "purge_protection_enabled"  { type = bool
  default = false }
variable "tags"                      { type = map(string)
  default = {} }
